@echo off

::set /p image="chemin vers l'image ? : "
::C:\python36-64\python c_test_network.py --model model\bati_not_bati_lenet.model	--image ..\examples\image.png
::_____________________________bati_____________________________________________
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_93158_42.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_402123_21.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_459178_48.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_464534_17.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_470123_34.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_514906_49.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_537173_50.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_576393_29.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_606532_39.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_633745_28.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_640447_41.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_657008_44.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_688214_1.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_689878_2.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_747919_3.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_749115_43.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_787407_46.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\

C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_853572_47.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_885375_14.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_926770_20.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_926986_25.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_999327_32.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1016750_23.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1020403_24.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1032034_4.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1040500_27.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1095271_5.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1097931_6.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1105809_7.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1111042_36.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1120241_45.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1179370_13.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1182713_19.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1202852_35.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\

C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1221828_8.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1255118_30.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1309322_16.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1314328_15.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1323402_9.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1355798_18.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1367408_37.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1414013_26.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1430996_10.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1453436_11.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1462731_22.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1550521_40.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1590827_31.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1605172_12.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1771091_38.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\bati\  --image output_1817761_33.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
::__________________________________non-bati_______________________________________
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_65116_25.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_127396_40.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_221481_27.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_245775_47.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_302042_48.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_370375_49.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_374510_50.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_445194_46.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_471784_1.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_515715_2.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_586777_42.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_618833_45.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_627659_3.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_654526_39.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_687635_4.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_695174_43.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_752549_28.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\

C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_759261_5.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_786860_41.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_836183_6.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_840929_7.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_893895_8.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_903268_34.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_903268_34.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1030557_10.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1054899_11.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1072366_12.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1088356_13.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1179592_14.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1218801_15.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1296209_23.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1299678_16.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1308861_17.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1368575_18.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\

C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1380376_19.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1466245_29.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1513974_38.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1526802_20.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1550064_31.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1651588_30.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1725582_26.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1768026_37.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1773321_33.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1786529_21.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1788123_36.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1791602_32.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1802815_24.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1899734_22.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1932050_44.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
C:\python36\python C:\_IA\bati_pas_bati\py_geoportail\test_3\3_test_network.py --model C:\_IA\bati_pas_bati\py_geoportail\model\bati_non-bati_geoportail_test_3.model --chem C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\test\non_bati\  --image output_1970649_35.jpg --result C:\_IA\bati_pas_bati\data\carreaux\50mx50m\geoportail\result\test_3\
::pause